[package]
name = "drawsvg"
version = "0.1.0"
edition = "2021"

[dependencies]
# gl = "0.14.0"
hex = "0.4.3"
num-traits = "0.2.19"
quick-xml = "0.36.0"
sdl2 = { version = "0.37.0", features = ["bundled"] }
