[package]
name = "drawsvg"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.22.1"
gl = "0.14.0"
hex = "0.4.3"
num-traits = "0.2.19"
once_cell = "1.20.2"
png = "0.18.0"
quick-xml = "0.37.0"
regex = "1.11.1"
sdl2 = { version = "0.37.0", features = ["bundled"] }
